services:
  envoy:
    build:
      dockerfile: ../shared/envoy/Dockerfile
    ports:
    - "${PORT_PROXY:-8443}:443"
    - "${PORT_ADMIN:-10001}:10001"
  backend:
    build:
      context: ../shared/echo

