version: '3'
services:
  envoy:
    network_mode: "host"      
    image: envoyproxy/envoy:dev-33c326495228e061be26632f79379d5d97ebd0e3
    ports:
      - "8000:8000"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
